version: "3"
services:
    apprest:
        image: docker.jala.pro/docker-taining/aspnetapp:compose
        build:
            context: .
            dockerfile: multistage.Dockerfile
        container_name: 
            hostInfoApp
        restart: always            
        ports:
            - 8085:80
        networks: 
            - hostInfoNet 
        depends_on: 
            - jenkins
        volumes:
            - app_vol:/app
        
    jenkins:
        image: jenkins/jenkins:lts-jdk11
        container_name: jekinsApp        
        restart: always
        networks: 
            - hostInfoNet                
        ports: 
            - 8080:8080
            - 50000:50000
        depends_on: 
            - sonarqube
        volumes:            
            - jenkins_data:/var/jenkins_home            
        
    sonarqube:
        image: sonarqube:8.9.0-community
        restart: always
        container_name: sonarqubApp
        environment: 
            SONAR_JDBC_URL: jdbc:postgresql://postgredbApp:5432/sonardb
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonaradmin
        networks: 
            - hostInfoNet
        depends_on: 
            - database
        ports:
            - 9000:9000
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/sonarqube_extensions
            - sonarqube_logs:/opt/sonarqube/logs
    
    database:
        image: postgres:12.1-alpine
        container_name: postgredbApp
        restart: always
        environment: 
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonaradmin
            POSTGRES_DB: sonardb
        depends_on: 
            - nexus
        ports:
            - 5432:5432
        networks: 
            - hostInfoNet
        volumes: 
            - database_postgresql:/var/lib/postgresql
            - database_postgresql_data:/var/lib/postgresql/data
        
    nexus:
        image: sonatype/nexus3
        container_name: nexusApp
        restart: always        
        networks: 
            - hostInfoNet
        ports:
            - 8081:8081
            - 8082:8082
            - 8083:8083            
        volumes:
            - nexus_data:/nexus-data
        
volumes:
    app_vol:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:    
    jenkins_data:
    nexus_data:
    database_postgresql:
    database_postgresql_data:

networks: 
    hostInfoNet:        
